version: "3.7"

services:
  systemd_watcher:
    image: systemd_watcher
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/systemd_watcher/data
      - ./database.db:/db/db.db
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:1.13.3
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - systemd_watcher
