version: "3.9"

x-systemd-watcher-config: &systemd-watcher-config
  SECRET_KEY: "mys3cr37k3y"
  DEBUG: "0"
  ALLOWED_HOSTS: "*"

services:
  systemd_watcher:
    image: systemd_watcher
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *systemd-watcher-config
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - systemd_watcher
